### ISSUE TITLE
On-screen keyboard and its settings doesn't work

### ISSUE THREAD

**Issue by welaq** [elementary/switchboard-plug-a11y#37] opened 2018-07-10 19:56 UTC
On Juno Beta when I turn on on-screen keyboard nothing happens. When I click on "On-screen keyboard settings..." nothing happens.

**Comment by leonardo-lemos** [comment] 2018-07-10 20:33
It seems that Onboard is not included in the ISO.

**Comment by arshubham** [comment] 2018-07-11 04:10
I reported this bug a few days back https://github.com/elementary/switchboard-plug-a11y/issues/34 however due to onboard crashes the fix was backed out.

**Comment by codygarver** [comment] 2018-07-11 06:30
Duplicate of reopened #34

**Closed by codygarver** 2018-07-11 06:30 UTC
Labels: Priority: High, Status: Confirmed
